### ISSUE TITLE
How to apply config changes?

### ISSUE THREAD

**Issue by stone-w4tch3r** [Ubiquitine/virtual-desktops-only-on-primary#3]
Hi! First of all, thanks for this script! It does what it promises =)

I faced issue with applying changes: if I change primary monitor or disable script in kwin settings, I need to relogin for changes to occur.

Is it possible to force apply them?

**Comment by Ubiquitine** [comment]
If you simply disable the script, your opened windows would remain in the same state as they were when the script was enabled. Namely, the windows on the secondary monitor would remain pinned to all desktops. Same would happen if you change the primary monitor. The script doesn't unpin already pinned windows - this is by design to allow user to pin windows to all desktops even on primary monitor.
Unfortunately, KWin does not provides functionality to notify the script that it was being disabled, so it not possible to revert any changes done by the script before it is disabled. 
For other cases, like changing your primary monitor, you don't have to actually log out. Disabling and then re-enabling the script should work.
