### ISSUE TITLE
Pls update

### ISSUE THREAD

**Issue by Twig6943** [Ubiquitine/virtual-desktops-only-on-primary#6]
doesnt seem to work with latest plasma (Nobara linux)

**Comment by Ubiquitine** [comment]
Pls provide more details about the issue.
Did it work before?
What Plasma version do you have? I'm not familiar with Nobara linux, the script is tested on KDE Neon and Artch Linux, which both use vanilla Plasma 6. 
ALSO: This script works best with the built-in display, e.g. laptop, when you connect an external monitor as a secondary display. Other combinations might not work properly because of unpredictable display management. There are some configuration in the script that I introduced to try and overcome some cases, but it requires you to determine the names of your displays and put the name of your primary display. Eve after that there is no guarantee that the script would work properly. This is because the display management is not done by KWin, so Kwin does not control which display is a primary one - which one is the first in the list of the outputs.

**Comment by Twig6943** [comment]
I have 2 monitors (desktop pc) 
![image](https://github.com/user-attachments/assets/5de4fcb9-6001-415c-a937-7d520cf89fcc)

KDE versions
![image](https://github.com/user-attachments/assets/94dbd500-7003-4f97-a6b9-088363ed0ca1)

**Comment by Twig6943** [comment]
Nvm it worked when I installed from kde's search menu instead of just adding the file
